import thePsychologyOfMoney from './assets/thePsychology_of_money.jpg';
import atomicHabits from './assets/books/Atomic_habits.jpg';
import deepWork from './assets/books/deep_work.jpg';
import thinkAndGrowRich from './assets/books/Think_and_Grow_Rich.jpg';
import almanackOfNaval from './assets/books/the_almanack_of.jpg';
import richDadPoorDad from './assets/books/rich_dad_poor_dad.jpg';
import cantHurtMe from './assets/books/Cant_hurt_me.jpg';
import startWithWhy from './assets/books/start_with_why.jpg';
import ikigai from './assets/books/Ikigai.jpg';
import youCanWin from './assets/books/you_can_win.jpg';
import sevenHabits from './assets/books/the_7_habits_of_highly_effect.jpg';
import makeYourBed from './assets/books/make_your_bed.jpg';
import yourBrainAtWork from './assets/books/your_brain_at_work.jpg';
import mindset from './assets/books/Mindset.jpg';
import grit from './assets/books/Grit.jpg';
import howToWinFriends from './assets/books/how_to_win_friends_and_influence.jpg';

import zeroToOne from './assets/books/zero_to_one.jpg';
import fourAgreements from './assets/books/the_four_agreements.jpg';
const books = [
  {
    id: 1,
    title: 'The Psychology Of Money',
    author: 'Morgan Housel',
    price: 480.00,
    oldPrice: 'Rs. 550.00',
    discount: '13%',
    image: thePsychologyOfMoney,
    category: 'Finance',
    inStock: 3,
  },
  {
    id: 2,
    title: 'Atomic Habits',
    author: 'James Clear',
    price: 520.00,
    oldPrice: 'Rs. 580.00',
    discount: '10%',
    image: atomicHabits,
    category: 'Self-Help',
    inStock: 5,
  },
  {
    id: 3,
    title: 'Deep Work',
    author: 'Cal Newport',
    price: 399.00,
    oldPrice: 'Rs. 499.00',
    discount: '20%',
    image: deepWork	,
    category: 'Self-Help',
    inStock: 0,
  },
  {
    id: 4,
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    price: 350.00,
    oldPrice: 'Rs. 450.00',
    discount: '22%',
    image: thinkAndGrowRich,
    category: 'Finance',
    inStock: 3,
  },
  {
    id: 5,
    title: 'The Almanack of Naval Ravikant',
    author: 'Eric Jorgenson',
    price: 430.00,
    oldPrice: 'Rs. 510.00',
    discount: '16%',
    image: almanackOfNaval,
    category: 'Entrepreneurship',
    inStock: 1,
  },
  {
    id: 6,
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    price: 470.00,
    oldPrice: 'Rs. 560.00',
    discount: '16%',
    image: richDadPoorDad,
    category: 'Finance',
    inStock: 8,
  },
  {
    id: 7,
    title: 'Can’t Hurt Me',
    author: 'David Goggins',
    price: 390.00,
    oldPrice: 'Rs. 480.00',
    discount: '18%',
    image: cantHurtMe,
    category: 'Self-Help',
    inStock: 20,
  },
  {
    id: 8,
    title: 'Start With Why',
    author: 'Simon Sinek',
    price: 360.00,
    oldPrice: 'Rs. 420.00',
    discount: '14%',
    image: startWithWhy,
    category: 'Entrepreneurship',
    inStock: 5,
  },
  {
    id: 9,
    title: 'Ikigai',
    author: 'Héctor García & Francesc Miralles',
    price: 300.00,
    oldPrice: 'Rs. 390.00',
    discount: '23%',
    image: ikigai,
    category: 'Self-Help',
    inStock: 0,
  },
  {
    id: 10,
    title: 'You Can Win',
    author: 'Shiv Khera',
    price: 340.00,
    oldPrice: 'Rs. 410.00',
    discount: '17%',
    image: youCanWin,
    category: 'Self-Help',
    inStock: 0,
  },
  {
    id: 11,
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    price: 410.00,
    oldPrice: 'Rs. 490.00',
    discount: '16%',
    image: sevenHabits,
    category: 'Self-Help',
    inStock: 6,
  },
  {
    id: 12,
    title: 'Make Your Bed',
    author: 'William H. McRaven',
    price: 370.00,
    oldPrice: 'Rs. 430.00',
    discount: '14%',
    image: makeYourBed,
    category: 'Self-Help',
    inStock: 0,
  },
  {
    id: 13,
    title: 'Your Brain At Work',
    author: 'David Rock',
    price: 390.00,
    oldPrice: 'Rs. 470.00',
    discount: '17%',
    image: yourBrainAtWork,
    category: 'Self-Help',
    inStock: 8,
  },
  {
    id: 14,
    title: 'Mindset',
    author: 'Carol S. Dweck',
    price: 440.00,
    oldPrice: 'Rs. 510.00',
    discount: '14%',
    image: mindset,
    category: 'Self-Help',
    inStock: 0,
  },
  {
    id: 15,
    title: 'Grit',
    author: 'Angela Duckworth',
    price: 320.00,
    oldPrice: 'Rs. 400.00',
    discount: '20%',
    image: grit,
    category: 'Self-Help',
    inStock: 6,
  },
  {
    id: 16,
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    price: 350.00,
    oldPrice: 'Rs. 420.00',
    discount: '17%',
    image: howToWinFriends,
    category: 'Self-Help',
    inStock: 0,
  },
  {
    id: 17,
    title: 'Zero to One',
    author: 'Peter Thiel',
    price: 460.00,
    oldPrice: 'Rs. 520.00',
    discount: '12%',
    image: zeroToOne,
    category: 'Entrepreneurship',
    inStock: 3,
  },
  {
    id: 18,
    title: 'The Four Agreements',
    author: 'Don Miguel Ruiz',
    price: 430.00,
    oldPrice: 'Rs. 500.00',
    discount: '14%',
    image: fourAgreements  ,
    category: 'Self-Help',
    inStock: 0,
  },
];

export default books;
